// ActionTypes.js
export const ADD_ACADEMIC_FORM = 'ADD_ACADEMIC_FORM';
export const DELETE_ACADEMIC_FORM = 'DELETE_ACADEMIC_FORM';
export const UPDATE_ACADEMIC_FORM = 'UPDATE_ACADEMIC_FORM';
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const ADD_WORK_FORM = 'ADD_LIST_FORM';
export const DELETE_WORK_FORM = 'DELETE_LIST_FORM';
export const UPDATE_WORK_FORM = 'UPDATE_LIST_FORM';
